### ISSUE TITLE
Survey fails to publish form to ArcGIS Portal

### ISSUE THREAD

**Issue by mindzia** [Esri/Survey123Community#109]
Survey123 fails publish form to ArcGIS Portal with "Enable Editor Tracking" option enabled.
Throws error "Enable archiving failed".
![survey123](https://cloud.githubusercontent.com/assets/12560743/7934470/6e0462a6-0930-11e5-8ddf-75b0f8dfa32e.jpg)

Without editor tracking, form can be published successfully.

**Comment by Miguelicus** [comment]
Some of my colleagues, as well as I have been experiencing an error as well:
![image](https://cloud.githubusercontent.com/assets/9654206/7940135/dd25a788-0946-11e5-9fb0-509c07edbbde.png)

Any ideas what could have happened?

Publishing forms worked fine yesterday.

**Comment by survey123** [comment]
@Miguelicus 
The Survey123 web service that converts XLSForms is temporarily down. Apologies for the inconvenience. Until we fix the problem you will not be able to use Survey123 Connect. We will try to fix this as soon as possible.

**Comment by survey123** [comment]
Thank you all for your patience. The XLSForm conversion web service is back online. Please try converting your forms again.

**Comment by mindzia** [comment]
By opening this issue I have in mind that publishinf form to ArcGIS Online is working fine, i.e. form can be published with editor tracking enabled. But if I am trying to publish the same form to my own Portal - publishing fails if editor tracking is enabled. I get error attached in my first message. If I disable editor tracking, everything works ok.

**Comment by survey123** [comment]
@mindzia 
We cannot reproduce this problem in our end.
Lets make sure that your Portal for ArcGIS meets the minimum requirements:
* Portal for ArcGIS 10.3.1
* Configured with a 10.3.1 ArcGIS Data Store 
* Configured to use built-in users. That is, not configured to use Enterprise Logins.
If the above is all in place, please specify:
* Operating System used for Portal and your ArcGIS Data Store
* Locale of your Operating System

**Comment by mindzia** [comment]
Hello,
I have tested on:
Portal for ArcGIS 10.3.1
Configured with a 10.3.1 ArcGIS Data Store 
Configured to use built-in users
Portal OS: Windows2008R2 English (US) chcp = 437
Client side OS Windows 8.1, by default I'm using Lithuanian locale. Have tried switching to English (US)
Survey123Connect version 1.0.108

Error occurs while application tries to Enable Editor tracking. On Portal directory and only  "FeatureLayer" and "CodeSample" items are created.

Regards

**Comment by survey123** [comment]
@mindzia 
Can you try removing your image type of questions from the Survey?
We tested publishing to Portal and we find the error you describe when we add an image type of field to the survey.  **Could you please confirm?** If this is indeed the problem, we are one step closer to resolve it.

**Comment by mindzia** [comment]
Yes! Exactly, after removing image field type, form was uploaded into Portal for ArcGIS. Hope you will fix it soon.

**Comment by survey123** [comment]
@mindzia 
We made a minor change to Survey123 Connect in version 118 trying to accommodate your scenario.
Would you please download v118 and try again?

Just a few things to keep in mind:
* We noticed that at times Portal for ArcGIS is not cleaning up correctly some tables in the Data Store. This causes some issues when attempting to publish a Survey the second time if you keep the Survey Name the same.
* We have run into publishing errors when using long Survey names. This is due to the fact that the name of your Survey is used to create tables in the ArcGIS Data Store. To keep things simple name your xls files with strings that are shorter than 12 characters and do not use spaces or special characters.

We need to investigate more on this but we hope the last build will help you keep going.

**Comment by mindzia** [comment]
Hello,
after version upgrade to 118, everything works OK. Thank you!
