### ISSUE TITLE
Auto-Suggest style dropdowns for Select_One questions

### ISSUE THREAD

**Issue by nemecb** [Esri/Survey123Community#125]
It would be be great to include an auto-suggest style drop-down in the product so that large lists of objects can be navigated through and selected as you start to type.

**Comment by vxsunstriderxv** [comment]
+1

**Comment by mwaltuch** [comment]
+1

**Comment by jshepherd42** [comment]
+1. This would be a massive time saver for us. We are an ecology company and I want to be able to send out our ecologists with select_one fields for species names. Even with cascading selects there can be hundreds of choices at the species level, which means they just won't bother using the predefined values and instead we get a shorthand version of the names, which can take hours to fix up back in the office.

**Comment by sirws** [comment]
+1.  GeoForm already has this EXTREMELY useful capability.  You can choose a standard select or a filter select.  AND, the filter select is not just a "starts with" search.  It searches the entire string for the characters you type.  See below.

![image](https://cloud.githubusercontent.com/assets/793576/10678942/46beec70-78ca-11e5-9291-901d1a25b7d3.png)

![image](https://cloud.githubusercontent.com/assets/793576/10678934/3a75879e-78ca-11e5-8b02-e3fddc2a3486.png)

**Comment by travisbutcher** [comment]
+1 Many clients will have large domains (species list etc) that scrolling through is a hassle.  We need the form to be smart enough to search and select items quickly.

**Comment by scoxisda** [comment]
+1
I have drop-down lists that have over 2,500 choices. My field staff will revolt if they need to scroll through that many choices. Survey123 looks to be a great product with many of the features that I need. The ability to do a filter search however is a must for my organization. Without it I will need to look to another product. Please add this feature.

**Comment by DShokes** [comment]
Excellent enhancement. Although, does it need to be restricted to select_ones? Take a look at  [jQuery Combobox](http://jqueryui.com/autocomplete/#combobox). This style provides a filterable drop down for select_ones. 
However, it would also be a great way to provide a drop down of suggested values for simple text field. This would save soooo much time wasted updating or republishing services just because a new value needs to be added to a domain. This also removes the need for an 'or_other' field which means your working with the true list of unique values in a single field. 

The option to restrict edits to values from the list should be up to the survey designer.

[So many ways a drop down could behave](http://skirtlesden.com/articles/extjs-comboboxes-part-1)

**Comment by bizzy1971** [comment]
+1

**Comment by survey123** [comment]
Tentatively adding this to the Refugee Day milestone June 20th 2016.

**Comment by survey123** [comment]
A new appearance has been added to the Advanced template called autocomplete. Use it with your Select_One questions. More details here: https://geonet.esri.com/groups/survey123/blog/2016/06/23/international-public-service-day-update

@bizzy1971 @DShokes @scoxisda @travisbutcher @sirws @jshepherd42 @mwaltuch @nemecb @vxsunstriderxv
