### ISSUE TITLE
Error while publishing a new survey

### ISSUE THREAD

**Issue by hhkaos** [Esri/Survey123Community#132]
I'm using Survey123Connect and I'm trying to publish my first service but I'm receiving 2 errors:

![2015-07-13_08h51_03](https://cloud.githubusercontent.com/assets/826965/8645553/af0b51e6-2948-11e5-9f07-94a1626cfd55.png)
![2015-07-13_08h48_54](https://cloud.githubusercontent.com/assets/826965/8645556/b269791c-2948-11e5-8785-3b6d3320f3b1.png)

Do you know what can be happening?. My colleague Isaac can do it but me following the same procedure can't.

Thanks!
Raul
BTW: congrat I like this tool too much, it is very powerfull. Just one suggestion, improve the graphic interface, the apps are very ugly ;P and the UX can be improved

**Comment by survey123** [comment]
Hi!

  when a survey is published, we create a folder in your user's content and inside it we put a feature layer (feature service), web map and survey item (code sample with an attachment). It looks like Survey123 Connect is trying to create a folder that already exists, hence the error message you get.  Please refer to issue #37 for details on how to address this.\

  In the second error, this is most likely due to the fact that your user may not have proper permissions to publish (create hosted feature layers, create content and share with groups).  This error also shows when you are using a Public Account.

  We are working on addressing both of the issues above. See #105 and #37 

  Thanks for your feedback.

**Comment by hhkaos** [comment]
I have just tried from my Mac and it worked fine using the same user account (it's a developer account). Tomorrow I will check again from my Windows machine removing the existing folders and I'll let you know.

Thank you very much for you help!

**Comment by survey123** [comment]
@hhkaos 
Hi Raul, we have updated the Survey123 Connect installer (build 130) . Please give it a try now. We have modified Connect so you get a more proper description when signing in with a user with insufficient permissions. The issue overwriting surveys ( #37 ) will remain.
