### ISSUE TITLE
Error creating a new survey

### ISSUE THREAD

**Issue by caiovicter** [Esri/Survey123Community#139]
When I try to create a new survey I get the error below:
![survey123_error](https://cloud.githubusercontent.com/assets/13632159/9048534/45010ad8-3a10-11e5-86fe-bb0f2c37138a.PNG)
Seams it's a problem with the name of the file, in Portuguease the name has this character (´). If I change the name of the form, taking out this character, the form works and I can publish it.

**Comment by survey123** [comment]
Thanks Ciao.
Good catch. We will look into this.
@caiovicter

**Comment by survey123** [comment]
This issue is caused by a non ASCII character being used in the default name of the form.  For the moment, to avoid this problem you will need to manually set the name of the form you want to create and ensure that it does not have any especial characters. Do not use the default name provided by Survey123 Connect. 

This affects every non-English locale where the default form filename has been localized using non ASCII characters.

We are investigating the issue further.

**Comment by caiovicter** [comment]
Ok! Thanks!

**Comment by survey123** [comment]
@caiovicter 

Please check [latest version of Connect](https://geonet.esri.com/groups/survey123/blog/2015/09/01/random-acts-of-kindness-update-september-1st-2015 ). We incorporated fixes to address this issue.
Thanks a lot for your feedback!

https://geonet.esri.com/groups/survey123/blog/2015/09/01/random-acts-of-kindness-update-september-1st-2015
