### ISSUE TITLE
Sending Survey Error 400 with Signature

### ISSUE THREAD

**Issue by CPolley7** [Esri/Survey123Community#146]
When Sending survey with a Signature I get an Error 400, when I remove the Signature from the form and send the survey it completes. Any Ideas?

**Comment by CPolley7** [comment]
The problem is not just with signatures its with all attachments.

**Comment by survey123** [comment]
I would recommend making sure that you are on a good, strong internet connection (preferably wifi) in order to sync records with attachments. The file size of the attachments can be large and take time to sync, any interruption in the internet service during the upload could cause it to fail. This is the same for signature, photos, etc.

**Comment by CPolley7** [comment]
This form was created with the blank template then I moved to the other template that had samples already in it and it worked fine.

**Comment by CPolley7** [comment]
Not sure its an internet connection , it ss
