### ISSUE TITLE
Blank option for Multiple Choice questions should be last or first

### ISSUE THREAD

**Issue by ltylka** [Esri/Survey123Community#163]
When looking at the Multiple Choice question labels, the second option is blank.  I believe the intent is to have the option to leave the question blank if it is not a required question.  However, having the blank option show up second in the list is very confusing.  Please see the screenshot below to reference the issue described.

![blank second option](https://cloud.githubusercontent.com/assets/8739256/9617232/1b9106b2-50c7-11e5-96ce-fd699ba36d14.PNG)

**Comment by survey123** [comment]
Hi Lana! Thanks for your feedback. We agreed this is not ideal. We will have this fixed in our next update in October. We will leave an option for people who do not want to choose anything in the list, but we will present it better.  In case where you want people to always input something, you will be able to set the question as 'required'.

**Comment by survey123** [comment]
Fixed on build 1.1.4. Closing.
