### ISSUE TITLE
Required Signature Image, Cant submit survey

### ISSUE THREAD

**Issue by RKnepper3** [Esri/Survey123Community#166]
I posted in geonet and was asked to repost here as its an issue. If you set up a signature image and make it required Survey123 does not recognize if a signature is done so you cant send your survey.

**Comment by survey123** [comment]
Thanks Ron. Good catch. We will keep this issue in the backlog and change its status once we understand better how to go about it.

**Comment by survey123** [comment]
@RKnepper3 
We have updated the Connect setup (v 1.1.4) to hotfix this #167 
v 1.1.4 also has a first round at the fix for the signature issue you found.
You can use the 'Validate Input' button in Connect to simulate what the behavior would be in the app.
Our plan is to make this fix available in the app in our October 1st update. 

![untitled](https://cloud.githubusercontent.com/assets/10968332/9770599/d8201f9c-56e5-11e5-9ec8-2ae4dc9899ea.png)

**Comment by survey123** [comment]
Fixed on build 1.1.4. Closing.
