### ISSUE TITLE
Send Error Code 1000

### ISSUE THREAD

**Issue by abrazell** [Esri/Survey123Community#213]
This error is received when trying to send a completed survey back to arcgis online.  The survey works as intended.  See attached screenshot of full error message.

![screenshot_2015-10-19-09-56-35](https://cloud.githubusercontent.com/assets/15106801/10583087/0bacd3cc-7659-11e5-8fb1-1713f30bf964.png)

**Comment by survey123** [comment]
Hi Andrea, you get this type of error when you add two geopoint questions to your form. Please have a look at #212 for more details. 

In your particular form, I got things to work when I put your room geopoint question within a repeat. That is, you go into a building and capture the location of the building (first geopoint question). Then you go into every room and capture the location of the room (second geopoint question). If you keep the room questions within a repeat (one building may have one or more rooms) you are allowed to have a second geopoint question.

**Comment by pablocarranza** [comment]
Hello, I have a question , someone will have a solution to this, thank you.

![2016-04-13 19 04 20](https://cloud.githubusercontent.com/assets/18452753/14513604/25e8185a-01af-11e6-8803-35f57b46e2be.png)

**Comment by survey123** [comment]
Hi Pablo. We can look at your specific issue. It will best if you could add this question into the Survey123 Group in Geonet at: https://geonet.esri.com/groups/survey123   When you add your question, please include the image as above and also include your XLSFile as an attachment so we can look into it in more detail. Very often the Error Code 1000 is caused by a mismatch between the data that is being sent from your phone and your survey feature service. I am sure we will be able to resolve this.  If we find that this is a software defect, we can come back to this repo and open a new enhancement request or bug.  Thanks a lot.

Typically, it is best to submit questions to the GeoNet forum, as we have a larger team of people monitoring it. For enhancement requests and bugs, this repo is a good place.
