### ISSUE TITLE
Required Fields ignored in repeats

### ISSUE THREAD

**Issue by RKnepper3** [Esri/Survey123Community#226]
It seems that if you put required fields within a repeat you can still submit them blank.  I have the statements below.  If I select yes to make the group relevant then it displays the repeat questions that are relevant and they are marked as required but you can submit without any data.

![capture](https://cloud.githubusercontent.com/assets/14116002/10675939/db020aba-78d0-11e5-9569-112d805129da.PNG)

**Comment by survey123** [comment]
Thanks Ronald. This is a known limitation at the moment. We added a note at the end of the Repeats section [here](http://survey123.esri.com/resources/XLSFormSupport/#repeats) when we released the last update to the app.  It is pretty well hidden we know... :)

We are hoping to get this fixed in the next update to the app.

Repeats in Survey123 do not support data validation for questions within the repeat. Any fields that are required, have constraints or have default values will not be honoured in repeats.

**Comment by ctoledo-img-com-br** [comment]
+1

**Comment by colgateg** [comment]
+1. As of 1.2.8 this still seems to be an issue.

**Comment by survey123** [comment]
@colgateg 
We are working on this issue and aiming in mid-May. If you would like to have access to a daily build to ensure that the new implementation works with your surveys, please email us at survey123@esri.com referencing this issue and asking for access to the daily.

**Comment by survey123** [comment]
Fix available now. Thanks for your feedback.
Please download the latest version of Connect and the field app.

Connect download available at: http://doc.arcgis.com/en/survey123/download/

**Comment by nicsi76** [comment]
Not really fixed! Still have the same issues...

**Comment by matthysjake** [comment]
++1... we are still experiencing the issue with 1.9.24...
