### ISSUE TITLE
Field Constraint with RegEx for Date not working

### ISSUE THREAD

**Issue by sirws** [Esri/Survey123Community#268]
In order to work around the date calendar picker limitations when dealing with older dates, I am trying to setup a regex to make sure the date is entered consistently.  I cannot seem to get anything to work.

http://regexlib.com/REDetails.aspx?regexp_id=1071

I put it in the constraint field like this:
regex(., '(((0?[1-9]|1[012])/(0?[1-9]|1\d|2[0-8])|(0?[13456789]|1[012])/(29|30)|(0?[13578]|1[02])/31)/(19|[2-9]\d)\d{2}|0?2/29/((19|[2-9]\d)(0[48]|[2468][048]|[13579][26])|(([2468][048]|[3579][26])00)))')

It always fires the constraint error even if I type in the proper date.

Any ideas?

**Comment by HannahFerrier** [comment]
Could you please clarify - are you still using the date field with the calendar picker? Or is this regex for a free text entry?

If you are using a date field, try previewing your survey in Survey123 Connect. Enter a date value and then select the 'Show Data Values' button. You will see that the value for you date is in **epoch time** (seconds since Jan 01, 1970).

Try writing your regular expression to validate epoch time values instead...

**Comment by sirws** [comment]
Sorry for the confusion.  I am using a free text field because of issues like this: https://github.com/Esri/Survey123Community/issues/242

I can get regex to work for email addresses, but I found a bunch of regex's formatting date strings online and I haven't been able to get any of them to work.

Thanks!

**Comment by survey123** [comment]
Closing
You can now change years and months.
Tap and hold to move quickly!
https://geonet.esri.com/groups/survey123/blog/2016/03/04/international-women-s-day-release
