### ISSUE TITLE
Alias definition

### ISSUE THREAD

**Issue by nicsi76** [Esri/Survey123Community#329]
Exporting the results of my survey to a geodatabase gives me in general a good result especially with my nested repeats being defined as relationship classes, which is already helpful. 
What I don't like is that now the alias of my fields are defined by the question (label) of my fields. That means, when my question is a bit longer then the whole question is put to the field name which looks awkward. I like the idea of having the option to define an alias to make a field name more meaningful. Is there maybe an esri-binding field option for the alias? Or maybe planned?

**Comment by bowlesgsrcx** [comment]
+1

**Comment by survey123** [comment]
@bowlesgsrcx @nicsi76 
Hi. In the International Children's Book release we added support for a new column (bind::esri:fieldAlias) in the Survey worksheet that lets you define the alias of your fields. Load a survey with the new Advanced template to see this new column. If empty, we will use the label for the field alias, otherwise, we will use whatever you put in this column.

Thanks again for your feedback.
@nicsi76 by the way: we will not be able to implement nested repeats anytime soon. We need to do some important changes to support nested repeats. We will look into that later in the year, but not in the short term. Just be aware so you do not get frustrated when you see no progress with your nested repeats.
Closing issue.

**Comment by nicsi76** [comment]
Thanks for the Alias, that's already very helpful! 
Regarding the nested repeats I will try to be patient. Unfortunately that's something our client would really like to have...

**Comment by simontheguide** [comment]
Hiya,

Does the Advanced template come with the new release of Survey123 connect? I downloaded from the ESRI site a week ago and the template did not contain the bind::esri:fieldAlias column. I added it to my survey and republished it but the labels are still being used as the Alias. 

In order to get the field names I need to download a GDB and choose 'show field names' instead of alias. Then, I can export the table for the science team to analyse the results. 

I know there used to be an option to use labels as aliases when you published surveys in Connect in older versions but that option no longer exists.

Where to I get the advanced template with the bind::esri:fieldAlias column added?

Cheers,
Simon

**Comment by JohnHasthorpe** [comment]
Hi Simon

The Advanced template is an online item, so it is always up to date. So if you create a new survey from Connect, you will get access to latest version which includes bind::esri:fieldAlias (this is still supported by the way).

The only exception to the above is when you create an survey from an existing Feature Service. In this case Survey123 uses a local copy of the template, which is part of the install. This version will be updated when you upgrade to the next version of Survey123. 

Please let me know if you need any further info and could I request that you use GeoNet to post your questions in the future. The forums there are much more active.

Thanks
John

**Comment by simontheguide** [comment]
Hi John,

Thank you for your reply.

Yes, I did create the survey in a new version of connect – but with an older survey that did not have the bind esri alias field. I published that survey then modified my survey with the added esribind alias field and re-published. I know now to create a new survey.

Yes, I will post future comments/questions in geonet.

Cheers for that,

Simon Allard
GIS Analyst
Bay of Plenty Regional Council Toi Moana
________________________________
P: 0800 884 880 DD: 0800 884 881 x8219
E: Simon.Allard@boprc.govt.nz<mailto:Simon.Allard@boprc.govt.nz>
W: www.boprc.govt.nz<http://www.boprc.govt.nz/>
A: PO Box 364, Whakatāne 3158, New Zealand
________________________________
Thriving together – mō te taiao, mō ngā tāngata

**Comment by JohnHasthorpe** [comment]
OK - it looks like you hit a bug. When you added the field alias and republished. A new feature service should have been created (with the new alias). This did not happen so the feature service was not update.

We do know about this one and have it in our backlog.

Thanks
John

**Comment by simontheguide** [comment]
Indeed,

Thanks for that.

Cheers,

Simon Allard
GIS Analyst
Bay of Plenty Regional Council Toi Moana
________________________________
P: 0800 884 880 DD: 0800 884 881 x8219
E: Simon.Allard@boprc.govt.nz<mailto:Simon.Allard@boprc.govt.nz>
W: www.boprc.govt.nz<http://www.boprc.govt.nz/>
A: PO Box 364, Whakatāne 3158, New Zealand
________________________________
Thriving together – mō te taiao, mō ngā tāngata
