### ISSUE TITLE
Default value if another field was filled with 'yes'

### ISSUE THREAD

**Issue by nicsi76** [Esri/Survey123Community#344]
To safe time and to avoid errors I would like to have the default value set to yes if another question before was answered with yes, too. How can I do that?

**Comment by DShokes** [comment]
put this in calculation: ```if(selected(${previous_field}, 'yes'), 'yes', '')```
This translates to if previous field is 'yes' then current field is 'yes', otherwise leave blank. You can nest these as well like this:
```
if  (
    selected(${added_product1}, 'Product1'), 
    1, 
    if  (
        selected(${added_product1}, 'Product2'),
        2, 
        if  (
            selected(${added_product1}, 'Product3'),
            3,
            0
            )
        )
    )
```
You can also hide your second field until previous_field is filled in by setting relevant to:
```not(selected(${previous_field}, '')```. second field will show when previous field isn't blank. if 'yes' was chosen, then it will default to 'yes'

**Comment by nicsi76** [comment]
Thank you DShokes, 
unfortunately it doesn't work for me. I have put `if(selected(${season1}, '1'), '1', '')` in the calculation field of the second field I want to set yes as default. In my choice list '1' is yes. I assume I have to put the name, not the label, right? At the moment nothing happens when I click yes on the first field.

**Comment by survey123** [comment]
@nicsi76 
@DShokes 
The issue seems to be related with select_ones. It looks like select_ones do not react to calculations. The expression would work against a text type of question, but not a select_one. We will look into this more closely to see if this is something we can resolve or if the current behavior is as expected.

Added a note here: https://geonet.esri.com/thread/173185

**Comment by nicsi76** [comment]
Thank you!

**Comment by DShokes** [comment]
Yes sorry. My second field is decimal. Also, I've noticed calculations on a
text field with relevance can cause previous fields to fault calculation.

**Comment by nicsi76** [comment]
We decided to skip that question :-) But thanks for your answer, it's still good to know.
