### ISSUE TITLE
Consideration in localizing "name" field on XLSForm spreadsheet?

### ISSUE THREAD

**Issue by yuki-26** [Esri/Survey123Community#367]
I know that “name” field on “Survey” sheet only works in English,
but are you considering that “name” field works in the Esri’s standard languages?
This field goes to field name of Feature Service on ArcGIS Online. 
That would be really helpful if you could make them display properly on there.

**Comment by survey123** [comment]
Hi @yuki-26   The NAME column only supports ASCII characters because this value is used to define the name of the column in your Feature Service. Databases cant create field names (columns) with non-ASCII characters or spaces.
If you would like to use non-ASCII characters you can use the Alias. By default, we set the alias of the column to be your LABEL. If you would like more flexibility, you can use the bind::esri:fieldAlias column in the XLS file. 

Thanks a lot for your question.  You may want to post questions in our GeoNet Survey123 Group at: https://geonet.esri.com/groups/survey123   We monitor regularly the GeoNet Group for questions and try to reserve this repo for software defect reports.
