### ISSUE TITLE
Error code 1000 String or binary data would be truncated. The statement has been terminated.

### ISSUE THREAD

**Issue by BootsyJ** [Esri/Survey123Community#375]
I keep getting this error and I don't know why. I have multiple selection fields. Is that a possible reason?

**Comment by survey123** [comment]
Hi. This error typically happens when a particular field in your feature service cannot keep all the data that is being sent to it.  For example, say you have a text field with a maximum number of characters equal to 50 and you try to put 55 characters in it.... then you get a 1000 error.

In a multi-select type of question, your choices are stored as a comma separated string. If your choices are made out of long strings or your text field is too small, you will get this error. 

Here are some suggestions:
1) In your choices worksheet, you can keep your labels long, but you will want to make your 'name' column values small.  Ultimately, what we store in your feature service is not the selected label, but its name (value).  This will help reducing the size of data stored in your feature service.
2) Use the esri::fieldLength column (at the far right end of your excel file) to explicitly set the length to a large enough number. By default, we created text fields with 250 characters, but you can make them bigger.  Using the schema preview in Connect you can truly tell how big the fields are going to be.

**Comment by BootsyJ** [comment]
I extended the field length to 5000 but I am still getting the same error. I also went into the choices tame and shortened the 'Name' column values.

**Comment by HannahFerrier** [comment]
I have seen this issue with select_multiple questions before. The value that is entered into the field for a select_multiple question is a comma separated list of all of the values that are selected. These lists can become very long, and if you have specified a field length that cannot hold all of the values, you will encounter this error.

Please use Survey123 Connect on the desktop to preview and fill out your form. Then you can use the **Show Data Values** button to preview the values that will be submitted into your feature service. This way, you can get a better idea of the size of the values of your select_multiple fields.

**Comment by survey123** [comment]
@BootsyJ 
If you keep getting this error, please share with us your XLSFile so we can have a closer look.

**Comment by jln1589** [comment]
I'm getting this same error.  It's strange though, because this form was working properly at the end of January but it broke sometime in the last couple weeks (could it have something to do with the new version that was pushed out at the beginning of March?).  I have "select_one" questions in my form and not the "select multiple."  As @HannahFerrier suggested, I used the Show Data Values to preview the size of the submitted values and everything seemed good.

**Comment by survey123** [comment]
@jln1589 
@BootsyJ 
Please share your XLSForms so we can have a closer look.
Thanks

**Comment by jln1589** [comment]
Should I just email my xlsform to survey123@esri.com?

**Comment by survey123** [comment]
@jln1589 
If your survey has sensitive information, email to suurvey123@esri.com
Otherwise, simply drag&drop in a comment here in the repo.  Some files can be attached to your comments in this repo.

**Comment by survey123** [comment]
@jln1589 
Thanks for sharing your Survey.
The problem was as follows:
* You had a Select_One question with a choice list that defined values as 0 and 1 (0 for Dispatched and 1 for Undispatched)
* Connect figured that since the values in your choice list were limited to one character, it created a field with length = 1. That is by design and expected.
* Then you had set the Default of the Select_One to 'Undispatched'
* When submitting, the app was sending the value "Undispatched" to a field which only had a length of 1, hence causing the Error Code 1000.
* Please note that the Default values need to match values in the NAME column of your choice list. You should have typed 1 instead of 'Dispatched'.  You will also note that once you use 1 instead of 'Undispatched', the dropdown will accordingly reflect the selection by default as 'Undispatched'.  If you keep 'Undispatched' as Default, no selection will be set by default, because there is no value in the list which such NAME.

**Comment by jln1589** [comment]
My issue was resolved.  I had a default value set up and I accidentally put the default value as a string when it should have been an integer since the default value was coming from a choice list with coded values.
