### ISSUE TITLE
How to get the Survey 123 App?

### ISSUE THREAD

**Issue by survey123** [Esri/Survey123Community#39]
People in the field use the Survey123 app to download your surveys and submit data to them. 

* If using Android:
    * Stable version **[available in the Google Play](https://play.google.com/store/apps/details?id=com.esri.survey123)** store
    * Latest build: https://rink.hockeyapp.net/recruit/e53ee3d66b234aaeb04b65298444e42d

* If using an iOS device:
    * Stable version **[available in the Apple Store](https://itunes.apple.com/us/app/survey-123-for-arcgis/id993015031?mt=8)**
    * https://rink.hockeyapp.net/recruit/08e13f6c0be44ad6ab179050d62941f7
    * We will process all requests manually due to restrictions redistributing Apple apps outside the Apple store. Once approved, you will get access to the App.

* If using your Mac

    * https://maps.esri.com/SP_DEMOS/qmlapps/Survey123/Survey123-Setup.dmg
    * This will install the Survey123 app in your Mac. Access will be immediate.

* If using a Windows PC

    * https://maps.esri.com/SP_DEMOS/qmlapps/Survey123/Survey123-Setup-x86.exe
    * This will install the Survey123 app in your PC. Access will be immediate.

* Survey123 App in the Windows Phone store is planned. Same for Blackberry 10.

**Comment by jmirmelstein** [comment]
@survey123 - The Windows PC link returns a 404.

**Comment by survey123** [comment]
@jmirmelstein 
Thanks!   Links above have been fixed.

**Comment by djibo** [comment]
Hi, I just downloaded and installed the app, but can't sign in to my ArcGIS Online account. When I initially setup my account I used my enterprise login (at the university where I work), so never setup a password with esri. On the Survey 123 app there's no place that I can find to sign in with an enterprise account, so do I need to setup a separate ArcGIS Online sign in for my existing account in order to use the app?
![ago signin](https://cloud.githubusercontent.com/assets/11965622/7164955/181aace4-e372-11e4-9a8e-89d79b307557.png)

**Comment by survey123** [comment]
@djibo 
Unfortunately, Survey123 at this moment does not support Enterprise Logins. It only works against ArcGIS built-in accounts.  We are looking at supporting Enterprise Logins. To track progress for support of enterprise logins check this issue: #60
