### ISSUE TITLE
Can't login with Survey123 Connect

### ISSUE THREAD

**Issue by bveldkamp** [Esri/Survey123Community#393]
When I try to login to AGOL using my organizational account, I only see a gray window with a spinning icon. 
Using Fiddler, I can see that I am actually logged in, a request to https://www.arcgis.com/sharing/rest/community/users/MYCORPUSERNAME returns some json containing my information.
Connect version is 1.2.62

![naamloos](https://cloud.githubusercontent.com/assets/7160755/14041465/6796d50e-f271-11e5-8b54-e5dfa4a76108.png)

**Comment by gzuknick** [comment]
Having the same issue

**Comment by Marie-Lou** [comment]
I've reported the same issue (#272) a few months ago.  This is due to OAuth sign in introduced a few versions ago, and your company's proxy settings blocks this.

On Windows, you can review your proxy settings by going Control Panel > Internet Options>Connections > LAN Settings. 

Note whether you have any of the following:
1. Automatically detect settings checked
2. Use automatic configuration script
3. Proxy server
Enterprise typically deploy proxy configuration via either methods 1 or 2 and not set option 3.

Unselect the Enterprise settings, and ONLY select the Proxy Server, and Bypass proxy server for local addresses

Hope this helps.....

**Comment by bveldkamp** [comment]
Hi Marie-Lou,

Thanks for your reply. Unfortunately this is a different issue: We don't have a proxy at our company at all. I also tried from home (without a proxy), but it didn't work there either. With or without Fiddler being active made no difference.

**Comment by HannahFerrier** [comment]
It looks like you are trying to sign into Survey123 Connect with a public ArcGIS Online account, or one that does not have publisher privileges.

Please make sure that your account has publisher privileges in ArcGIS Online, or use a different account that does.

- Hannah

**Comment by bveldkamp** [comment]
Hi Hannah,

That is a possibility. I do have a corporate account, but it looks like I am just a 'User'. I _can_ publish maps though...

Still, I'd expect a message saying I don't have publisher privileges, not a gray window.

**Comment by HannahFerrier** [comment]
I'm glad you got it working :) We do already have this issue logged as a bug with our development team.

**Comment by survey123** [comment]
This has been fixed in the Star Wars release.
The app and Connect will now show a meaningful message if the logged in user does not have sufficient privileges. Issues when connecting via OKTA have also been addressed. Closing issue.
