### ISSUE TITLE
Relevant based on a time value

### ISSUE THREAD

**Issue by travisbutcher** [Esri/Survey123Community#429]
We have a form where we would like the relevant values to be determined based on a time calculation.

For Example:
When was your last treatment?
If the date is over X day/weeks/months then show the block of questions if not then skip

**Comment by colgateg** [comment]
This may not be ideal, but this is one way to workout your issue...

![image](https://cloud.githubusercontent.com/assets/17730847/14545494/453c573e-0254-11e6-8657-d943b613fb8d.png)

DATE and DATETIME values are recorded as "epoch millisec since 01/01/1970 GMT"...
and the now() function is supported...

So if you put them together and do the math you will get reasonable resulting values for building out the relevant tests. Things to remember: 1 day = 86400000 milliseconds and don't forget to handle "now() - 0" because that is what will test true when the form starts up (datetime field cannot be null so it defaults to 0)...

We have been using [doc.arcgis.com](http://doc.arcgis.com/en/survey123/), [XLSFormSupport](http://survey123.esri.com/resources/XLSFormSupport/), [javarosa](https://bitbucket.org/javarosa/javarosa/wiki/Home), and [odk-xform-spec](https://opendatakit.github.io/odk-xform-spec/)... to piece together what is or isn't supported.

Hope this helps.

**Comment by survey123** [comment]
Some more additional info on Dates: https://geonet.esri.com/groups/survey123/blog/2016/04/11/international-childrens-book-day-release

**Comment by survey123** [comment]
Also some additional discussion here: https://geonet.esri.com/thread/175212
