### ISSUE TITLE
Surveys without geopoint

### ISSUE THREAD

**Issue by bowlesgsrcx** [Esri/Survey123Community#438]
We are getting data from a survey and are finding that if the phone service is non-existent or location services are not turned on for a device, we do not get a geopoint with the survey. Normally not a problem but we are using geoevent to send notification emails for each survey that is completed (typically around 30 per day) that are needed in as real-time as we can. When there is no geopoint data with the survey results, geoevent does not trigger and send the email. Is there any way around this where we can default in a lat/long? For this app, we are collecting all of our data at a known location (well pad). Is there anyway to force a point even at 0,0 if location services are not turned on or service is sparse?
Thanks,
--gary

**Comment by survey123** [comment]
Hi Gary.   I wonder if you can resolve this issue in GeoEvent Processor. For example, if the field user is adding the well pad id, you should be able to join the XY location from the well pad feature class to the survey. This could be something that you do only if the location is empty.

As far as Survey123 goes, the logic is that we add a NULL value if the device is not able to generate a location (either because location services are off, or because the device does not have such capability).  There are some devices that would not generate a location when used in airplane mode, or when not connected to the network, Typically these are devices who do not run a GPS.

There is no simple way to add a fake location when it is not set by the device. We would like to keep the behavior as it is, since NULL is clearly telling you that the device was not able to capture a location in the field.  I wonder if post-processing the data and applying your rule there would fit.

**Comment by yrebois** [comment]
Hi, 
this question could fit as well  the preload data with CSV forms

we are more or less in the same situation, we would like to do some monitoring of Wells in Allepo +240 wells and we already have the coordinates of the wells and our colleagues from the red crescent are doing regular assessment. 

**How could we ensure to have the point visible into arcgIS online  ? if a geopoint is not set up ?**
We were thinking to take the coordinates from a list of value we have them. either with a relevant field... or with a a calculate. 
in this case how do you calculate. 
is there a function "take value" from a list ? or something similar
As you see we are a bit stuck on this issue. 
It is a common scenario, when we are revisiting the site, we do not want to work with collector as there is no skip logic and other advanced fields ..

I am attaching a dummy   form , if one of you could propose a solution taht will be good 


Thank you  for your assistance@ elvin/ismael we could discuss next week in GVA in case of, but as we have working session in middle east region,until the end of the week it ill be appreciated to have your suggestions and ideas.  
thanks a lot
Yann and NAME
[ABM_Yann_Geolocation_pb_260416.xlsx](https://github.com/Esri/Survey123Community/files/236255/ABM_Yann_Geolocation_pb_260416.xlsx)

**Comment by spatialdude** [comment]
Hi

I've created the example below the demonstrates the idea using a select_one question and **substr** expressions to extract the borehole id and it coordinates.

The *trick* is that the select one choices name values are an aggregate of the borehole,longitude and latitude values. Each portion of the choice name value must be of a known specific length for the **substr** to work properly but its easy to adjust the example for different situations. The labels for each choice which the user sees can be whatever you want as per usual.

The example demonstrates using readonly questions if you want to present the details to the user or **calculate** questions if you don't need the user to see the values. In practice you would not do both and choose whatever makes sense in your own use case.

[Boreholes.xlsx](https://github.com/Esri/Survey123Community/files/237932/Boreholes.xlsx)
