### ISSUE TITLE
Failure to see .tpk 

### ISSUE THREAD

**Issue by MrPaulg** [Esri/Survey123Community#443]
We are using Survey 123 and I'm trying to use .tpk for offline work. I received and Arcgis Server Cache (10.2) and I have this are up and running on our 10.3.1 server.  I'm using Export MapServer Cache using the cache type of tile package. It does its thing and gives me a .tpk but this .tpk does not show up in Survey123, however if I create a .tpk from arcmap it works a dream, but unfortunately I can do this with a cached service from arcmap, hence I'm using the tool mentioned above.

I assumed it might be the cache storage format? however I tried to upgrade the storage format and it fails and actually now my cache just displays blank!... But not to confuse matters would you have any ideas on how to sort the .tpk not being visible issue? I have looked at all links etc. but so far no joy.

As a side note the .tpk that will not work in Survey123 works with collector.

Any help would be really appreciated, as we have setup our surveys ready to commence for the summer and just hit this brick wall.

Thanks in advance

Paulg

**Comment by survey123** [comment]
Hi @MrPaulg   I wonder if your Tile Package is in a projection other than Web Mercator Auxiliary Spehere. If that is the case, Survey123 will not be able to work with it.

**Comment by survey123** [comment]
Hi. @MrPaulg  Updated the [Prepare Basemaps for Offline use](http://doc.arcgis.com/en/survey123/desktop/create-surveys/preparebasemaps.htm) help topic. Please try again using Survey123 Connect for ArcGIS and the Survey123 mobile app on version 1.6.

[About the 1.6 release of Survey for ArcGIS](https://geonet.esri.com/groups/survey123/blog/2016/07/26/227-pi-approximation-day-release)

**Comment by Faran88** [comment]
Hello,

Very strange thing happened:-w
I prepared .tpk (UTM zone40) instead of Web Mercator Auxiliary Spehere. This .tpk is working fine with ipad and not showing on the android. When i check-in survey123 (mobile app) settings>Map library = the .tpk is there but not showing inside the form.

I repeat the same is shown on the ipad with the (UTM zone40).

I would highly appreciate your reply.

Thanks

**Comment by Farah1988** [comment]
Hello,

Very strange thing happened:-w
I prepared .tpk (UTM zone40) instead of Web Mercator Auxiliary Sphere. This .tpk is working fine with ipad and not showing on the android. When i check-in survey123 (mobile app) settings>Map library = the .tpk is there but not showing in the form.

I repeat the same is shown on the ipad with the (UTM zone40).

I would highly appreciate your reply.

Thanks

**Comment by JohnHasthorpe** [comment]
Hi Farah

Can you provide some more information:
- What version of Android are you using?
- What version of Survey123?
- How large is the .tpk?
- How did you create the .tpk (what application did you use)?

Thanks
John

**Comment by Farah1988** [comment]
Hello John,
Thanks for your reply. Please find the info below

Samsung Galaxy Tab A 6 - Android Version 7.0Survey123 Mob App version 2.3.29TPK is 7 GB, however, working fine with IOS and WindowsTPK was created through ArcMap.


Farah

**Comment by Farah1988** [comment]
[Survey123.docx](https://github.com/Esri/Survey123Community/files/1309701/Survey123.docx)

Screenshots of the environment

**Comment by JohnHasthorpe** [comment]
Thanks Farah - this is a known bug affecting Windows and Android (BUG-000107249).

I will add the information you provided to the bug issue.

Thanks
John
