### ISSUE TITLE
Error editing Survey123 Feature Service tables in ArcGIS Pro

### ISSUE THREAD

**Issue by phil-wilson** [Esri/Survey123Community#496]
We were told by ESRI the best way to view and edit the related tables and attachments of a feature service created by Survey123 was to use ArcGIS Pro. Main reason is because the related tables and attachments can not be viewed/edited in AGOL at present.

When trying to edit the attribute data in the tables via ArcGIS Pro (main or related) we get the following error:

Main table error:
![screenshot 1](https://cloud.githubusercontent.com/assets/19141448/16067998/5d60d0ec-3305-11e6-83a9-20554862d6ff.png)

Related tables error:
![screenshot 2](https://cloud.githubusercontent.com/assets/19141448/16068018/86b2c6d0-3305-11e6-90ef-82ba2087f07e.png)

**Comment by survey123** [comment]
Hi Phil, I am afraid this may have been caused by a software defect during our Beta phase. Would you please try the following:
1- Download Survey123 Connect 1.5: http://doc.arcgis.com/en/survey123/download/
2- Publish a brand new survey using  your existing XLSFile
3- Add some data with the Survey123 app and then try to edit from ArcGIS Pro

**Comment by survey123** [comment]
@phil-wilson 
Hi Phil, were you able to try the steps above?

**Comment by phil-wilson** [comment]
Hi there. I published a new survey with Connect 1.5 and tested again after entering new survey data as suggested. The same issue with ArcGIS Pro 1.2 remains and a rowid error returned when trying to edit.

Word from ESRI support is that this is a known bug with ArcGIS Pro 1.2 and will be fixed in ArcGIS Pro 1.3.

It means at present there is no way to edit related tables in a feature service created by Survey123.

**Comment by MKellyEsri** [comment]
Hi Phil - it may be worth trying to [edit through the ArcGIS Online item details page](https://doc.arcgis.com/en/arcgis-online/share-maps/item-details.htm#ESRI_SECTION2_4E37FBFFA35F4DBF98FD4AB7910CD9AC) (functionality that was added with the last update). This should help identify whether the problem is on the Survey123 side or the ArcGIS Pro side.

**Comment by phil-wilson** [comment]
@MKellyEsri 
Thanks for the suggestion to try editing related tables via the Data tab on the item details page. I wasn't aware this was possible. I have just tested and was able to successfully edit the related tables. Thanks. ESRI support is still working on a fix for ArcGIS Pro, which would be more ideal.

**Comment by phil-wilson** [comment]
This has now been fixed in the latest version of ArcGIS Pro 1.3.
