### ISSUE TITLE
Web Builder attachments

### ISSUE THREAD

**Issue by karmstro77** [Esri/Survey123Community#514]
I created a new survey using the web builder. The resulting feature service has attachments enabled (even though I did not specify that). However, when I open the app on my phone, i dont have the ability to add attachments. Is this expected behavior?

![image](https://cloud.githubusercontent.com/assets/6819070/16771375/475bc5c6-481e-11e6-973a-abcd77eb2c78.png)

![image](https://cloud.githubusercontent.com/assets/6819070/16771448/8b149748-481e-11e6-9ac2-4ed695c09217.png)

**Comment by zhif7782** [comment]
Hi @karmstro77 , you're right, that's the expected behavior. Enable attachments in the feature service from the web designer is for future usage (such as allowing you to add photos in the survey from a web browser). 
For now, if you expected to add photos in the native app, you have to add at least one "image" question in your survey, due to all behaviors respect to your designed questions. And also editing a survey created in web designer in Survey123 Connect will be delivered in the next few releases.
