### ISSUE TITLE
Submission URL Error on Survey Upload

### ISSUE THREAD

**Issue by ksditt** [Esri/Survey123Community#529]
I am trying to use a submission url in a new survey but I am getting an error when trying to publish, "The custom feature service submission url is not compatible with this survey (Request error).".  To create the feature service, I published a survey and downloaded the feature layer from that service, then used that feature layer's schema to create and publish a feature service. I created a new survey from the existing survey and added the submission url, but I cannot get the survey to publish. 
In the feature service, I have the editor tracking fields present, could this be causing the issue? 
Does the feature layer schema have to match the survey schema without editor tracking enabled? Also, do I need to add an ObjectID field to my survey schema?
![submissionurlerror](https://cloud.githubusercontent.com/assets/18285694/17371677/c5d8f66a-596e-11e6-9c35-64c25029651d.JPG)

**Comment by brg234** [comment]
I am also curious if it is possible to use a service from ArcSDE as the submission URL. I tested a lot of different scenarios, but have not had much luck so far.

**Comment by wparco** [comment]
Having the same problem. I did exactly as the OP thinking it would be the best way to get the schema right.

**Comment by ksditt** [comment]
We had a service call with ESRI yesterday and the rep informed us that the submission url will work ONLY in portal, not AGOL. Major bummer since that vital bit of info isn't documented anywhere that I've found. I am going to do some testing today to see if we can work it out using AGOL anyway, I'll make sure to let you all know if we have any success. Good luck.

**Comment by wparco** [comment]
That's a shame. I did find this blog post going into much greater detail about how to set Survey123 up to work on Portal. Unfortunately We don't have it setup due to IT problems, but if it's an option for you then it might be worth trying.
[https://geonet.esri.com/groups/survey123/blog/2015/07/29/survey123-and-arcgis-for-server]

**Comment by tedrick** [comment]
@ksditt - we reviewed the tech support incident that you had because submission url will work with ArcGIS Online in addition to Portal.  That being said, the submission url relies on setting up the tables in the submission url *exactly* the same as they would be as if Survey123 Connect was publishing them.  We are seeing some cases where that isn't possible due to database naming and other fairly subtle db-specifc issues.  Is it possible to follow up in more detail out of thread?

**Comment by vanessasimps** [comment]
@tedrick I would also like more information about setting this up via AGOL instead of Portal. I am going in circles trying to set this all up. Thanks in advance.

**Comment by tedrick** [comment]
@vanessasimps - New functionality to support existing services and the documentation was updated with the release in December (1.10) - if you aren't on that version I would recommend upgrading.  The documentation is at http://doc.arcgis.com/en/survey123/desktop/create-surveys/survey123witharcgisserver.htm

**Comment by vanessasimps** [comment]
Thank you @tedrick  I will give that a try. So far I am running into issues, but totally possible that it is operator error.
Can you tell me if there are limitations for linking a line/polygon feature services vs a point FS?

**Comment by tedrick** [comment]
Currently Survey123 only supports points.

BTW, the GeoNet forum is a more active venue for asking questions, including searching for existing ones - https://geonet.esri.com/groups/survey123

**Comment by vanessasimps** [comment]
@tedrick 
oops! sorry about that. I will book mark the link.

And thank you for your assistance, I appreciate it.
