### ISSUE TITLE
Login Survey123

### ISSUE THREAD

**Issue by Paisawan** [Esri/Survey123Community#81]
Hello, 

After I installed survey123conect.exe 

I open it up . I uploaded form using excel file and also created new form. 

Problem is ,

I try to singin to upload my form. 

But it shown error " Unable to generate token. Invalid username or password" it shown even my mobile app also. 

But I can use my username and password to login via http://survey123.esri.com/ 

I tried to use wifi and LAN connection. It didn't work. 

Any idea for my case ? 

Please share 

thank you

PK

**Comment by survey123** [comment]
Hi! 
What is the build number of your Connect app? You can see the number in the bottom left corner of connect as shown in the next image:

![buildnumber](https://cloud.githubusercontent.com/assets/10968332/7393531/3be2a830-ee43-11e4-8819-b70f39634045.png)

Please note that the user and password are case sensitive.

Sometimes the security configuration of a network can cause problems like this. See #33   We are hoping to have an update to Survey123 later this week or next which will include some fixes for internet proxies.

**Comment by Paisawan** [comment]
For me 

version is 1.0.60 

How can I update it?

It might be working. 

Thanks in advance. 
Paisawan

**Comment by survey123** [comment]
Hi, to download the latest version of Connect (build 65) simply login to http://survey123.esri.com and use the quick links at the bottom of the Survey Gallery.  
![untitled](https://cloud.githubusercontent.com/assets/10968332/7413247/d6211c40-eefe-11e4-8e4d-4d7b9ae4581c.png)
Note: We are planning to update again around May 4.

**Comment by Paisawan** [comment]
Now,I already updated but same still shown same error when I singin 

I use my personal laptop, window8 , wifi connection . 

Any idea about my error ?

![error](https://cloud.githubusercontent.com/assets/12165792/7414403/ac649fa2-ef7c-11e4-9f63-2ec4befe02be.PNG)

Thanks in advance

**Comment by jmirmelstein** [comment]
@Paisawan - do you use enterprise accounts in ArcGIS Online?  Is your account part of an Organization? Are you sure the Username/Password combination is correct?

**Comment by survey123** [comment]
@Paisawan   Could you please try Survey123 Connect (Build 1.0.81).  We added some more checks for Reverse Proxies. If this does not work, we will debug Connect within your own network while at Geneva the week of May 18.

**Comment by Paisawan** [comment]
Thanks a lot . Now I can login Survey123 ^^

**Comment by Paisawan** [comment]
I use the account that is part of an organization.  which type of account can we use in Survey123 ? 

We have to use subscription accounts ? is it difference with enterprise ?

I would like to know more about specification for account and ability to use survey123 as well ??

**Comment by survey123** [comment]
Hi. Glad to hear is finally working!
Essentially, you can configure your ArcGIS organization with either built-in accounts and enterprise accounts. A built-in account is one managed by ArcGIS (ArcGIS persists your user and password and takes care of authentication). An enterprise account, or enterprise login is one that is managed externally to ArcGIS. For example, you use enterprise logins when you make your ArcGIS account delegate authentication into Windows Active Directory or your own LDAP.    People like to use Enterprise Logins because in that manner end users can take advantage of their own existing accounts (no more passwords to remember) and system administrators can leverage their trusted enterprise user store.

Survey123, at the moment, does not support enterprise logins. We are working hard to support this, but we will need to wait until later in the year.  

By default, all ArcGIS Online organizations are setup with built-in accounts, but the ArcGIS administrator can change that as described here: http://doc.arcgis.com/en/arcgis-online/administer/enterprise-logins.htm  To understand what type of account you have in hand, it is best you ask your ArcGIS administrator.

**Comment by d3netxer** [comment]
@survey123 I have version 1.0.108 and I am receiving error " Unable to generate token. Invalid username or password" when trying to log-in
