### ISSUE TITLE
Lookup variable for calculation

### ISSUE THREAD

**Issue by DShokes** [Esri/Survey123Community#86]
A form has the following fields:
Species (text) - Select one
Diameter (decimal)
Dosage (decimal) - Calculated

Calculating Dosage = ${Diameter}*25 works fine. However, the 25 is actually variable based on Species. For example, here is rate chart:
Species    | Rate per Diameter
Ash          |  15
Birch        |  20
Cedar      |  15
Hawthorn |  10
Fir            |  25
Spruce     |  25

So the Dosage for an Ash with a Diameter of 10 would be 10*15=150

If the Rate per Diameter is a column for species in the choices sheet, how would the calculation formula be written for Dosage?

**Comment by survey123** [comment]
Hi, working on this one. Stay tuned. @DShokes

**Comment by MKellyEsri** [comment]
Is this not already possible with something like this:

[Calculate.xlsx](https://github.com/Esri/Survey123Community/files/112254/Calculate.xlsx)

Perhaps this is something that was added since this thread was opened. The only problem is that within the choices list, you may have the same name for multiple species.
