### ISSUE TITLE
Sample Form With Multiple Feature Templates And Subtypes.

### ISSUE THREAD

**Issue by DShokes** [Esri/Survey123Community#96]
The current sample form only builds 1 feature template and does not use subtypes:
```json
  "types" : [], 
  "templates" : [
    {
      "name" : "New Feature", 
      "description" : "", 
      "drawingTool" : "esriFeatureEditToolPoint", 
      "prototype" : {
        "attributes" : {
          "text_1" : null, 
          "integer_1" : null, 
          "decimal_1" : null, 
          "select_one_1" : null, 
          "select_one_otheer_1" : null, 
          "select_one_otheer_1_other" : null, 
          "select_multiple_1" : null, 
          "select_multiple_other_1" : null, 
          "select_multiple_other_1_other" : null, 
          "select_horizontal_one2" : null, 
          "numb" : null, 
          "date_1" : null, 
          "time_1" : null, 
          "date_required" : 0, 
          "text_default" : null, 
          "int_readonly" : null, 
          "int_calc" : null, 
          "cons_integer" : null, 
          "cons_decimal" : null, 
          "select_relevant" : null, 
          "select_multiple_relevant" : null, 
          "text_relevant" : null, 
          "skip_group" : null, 
          "select_animal" : null, 
          "text_multiline" : null, 
          "select_one_no_style" : null, 
          "select_minimal_one" : null, 
          "select_horizontal_one" : null, 
          "select_one_shapes" : null, 
          "select_compact_one" : null
        }
      }
    }
  ]
```
Is there are way to define multiple types and templates from the excel file? The addon called X-Ray for ArcCatalog has this functionality in an excel interface. It has been extremely useful designing subtypes for feature classes, which are then published.  
Thanks

**Comment by survey123** [comment]
Hi Davin, apologies for the belated response.
Survey123 translates your surveys into a data model that can support the questions and logic as described in your form.  Geodatabase subtypes and feature templates could be used to push down to the geodatabase part of the validation and logic in your forms. However, this translation can be at times arbitrary so we decided not to implement it. For example, subtypes could be handy to model one first level of cascaded selects.  In practice, a survey can include multiple levels of cascading, and even multiple questions with cascaded selects.  Selecting one of your cascaded selects and modeling it as a subtype would be an arbitrary call... How do know that we model as a subtype the exact cascaded select you want? Also, you would not have consistency: not every cascaded select would be modeled as a subtype group.
In the case of feature templates, the issue is that they are designed for map centric workflows. Introducing aspects such as default editing tools or cartographic representations are outside of the scope of the Survey authoring experience.

Having said the above, Survey123 is compatible with the Subtypes and Feature Templates you may want to create in a feature service. Try the following: first use Survey123 to create a feature service, then edit its definition to incorporate subtypes and feature templates.  You will want to make sure that things are consistent, or otherwise 'adds' may fail.

**Comment by DShokes** [comment]
Thank you for the detailed response. I underestimated the complexity of inferring subtypes. I will try to manipulate the templates after the feature service is created. It will help to see if it affects form
submissions. However, I don't think it will apply in production. My organization workflows also require related tables, which currently cannot be added after the hosted service is created.

**Comment by survey123** [comment]
You may want to try this too:
1) Publish Feature Service first with Survey123
2) Download the feature service data (empty) as a file geodatabase
3) Add related tables and templates in ArcMap
4) Publish as a new hosted  feature service
5) Get the URL of the feature service (dropping the /0 at the end) and paste it into Connect/Settings/Data
6) Publish survey again, but just the form this time.
7) Delete the service created originally to avoid confusion
8) Make sure the sharing of the survey and the feature service are consistent
